### ISSUE TITLE
error: stream error: stream ID 1; INTERNAL_ERROR

### ISSUE THREAD

**Issue by CristiVlad25** [vodafon/waybackrobots#2]
Upon running it with the latest version of go I get this error 

```
error: stream error: stream ID 1; INTERNAL_ERROR
```

**Comment by vodafon** [comment]
Hi @CristiVlad25

I have tested with go1.17 on Linux and Mac - it works well.
Please, give me your go version with arch, OS, and target domain.

**Comment by CristiVlad25** [comment]
Windows 10, go latest version 1.17, google.com

**Comment by CristiVlad25** [comment]
Fixed
